// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (-1016169464)
#define NOTOSERIF_14_FONT_ID (-1949882134)
#define NOTOSERIF_16_FONT_ID (-450474652)
#define NOTOSERIF_18_FONT_ID (2116598001)
#define NOTOSANS_12_FONT_ID (436936729)
#define NOTOSANS_14_FONT_ID (1319136511)
#define NOTOSANS_16_FONT_ID (1479557190)
#define NOTOSANS_18_FONT_ID (-893806)
#define UI_10_FONT_ID (-1557186678)
#define UI_12_FONT_ID (391709707)
#define SMALL_FONT_ID (166312473)
#define DICT_FONT_ID (2052812150)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(DICT_FONT_ID != 0, "Font ID collision with sentinel");
